barcode.lo: /home/andreas/Downloads/php-5.3.6/ext/barcode/barcode.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/andreas/Downloads/php-5.3.6/ext/barcode $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/andreas/Downloads/php-5.3.6/ext/barcode/barcode.c -o barcode.lo 
$(phplibdir)/barcode.la: ./barcode.la
	$(LIBTOOL) --mode=install cp ./barcode.la $(phplibdir)

./barcode.la: $(shared_objects_barcode) $(BARCODE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_barcode) $(BARCODE_SHARED_LIBADD)

